baseurl = "/"
languageCode = "en-us"
title = "Juooga Status"

[permalinks]
  incidents = "/incidents/:year/:month/:day/:slug/"

[params]
  defaultLogo = "https://cdn.juoo.ga/logo/juooga.svg"
  faviconsPath = "https://cdn.juoo.ga/logo/juooga.ico"

# List of systems monitored in this status page.
# You'll be able to change their status every time
# you open or update an incident.
# Replace these examples with your own system names.
systems = ["API", "CDN", "DNS", "Site delivery"]
